Fix ClassCastException
CoFH/ThermalDynamics-1.12-Legacy pull request #25
Opened 2019-07-22 07:30 UTC by jonatsp

Sometimes the TileEntity is not an instance of TileGrid and this can cause the player to be unable to log in and server log errors such as these:
https://paste.dimdev.org/huyegeguva.mccrash
https://forums.spongepowered.org/t/crash-with-thermal-dynamics-and-ae/29499
https://pastebin.com/fuuaUYCP
https://gist.github.com/tenten8401/3b07031bcf0646a51948906d5ad8e1c3

2019-09-03 09:54 UTC, covers1624 requested changes
Implementation is messy, please implement the suggestion.

2019-09-03 09:54 UTC, covers1624 commented on src/main/java/cofh/thermaldynamics/block/BlockDuct.java
> +		}
This is super messy, please change it to the following.
```java
TileEntity tile = world.getTileEntity(pos);
if (!(tile intanceof TileGrid)) {
	return;
}
TileGrid theTile = (TileGrid) tile;
```

2019-09-03 13:29 UTC, jonatsp commented
> 
> 
> Implementation is messy, please implement the suggestion.

Sorry, It's fixed

2019-09-05 03:57 UTC, covers1624 commented
Change looks good, I'm concerned because this commit was created on GitHub, have you tested your code?

2019-09-05 03:58 UTC, covers1624 approved these changes

2019-09-05 05:58 UTC, jonatsp commented
> 
> 
> Change looks good, I'm concerned because this commit was created on GitHub, have you tested your code?

I've used a modified version with my messy code (which fixed the crash) for two weeks and everything worked perfectly in the Forge 2838. After making the requested changes, I was able to build and play for a few minutes and it worked perfectly also.

2019-09-06 23:04 UTC, covers1624 commented
Alright.

2019-09-06 23:04 UTC, merged